#!/usr/bin/env bash
#
# Rebuilds teams.yaml: a snapshot of live GitHub team roster (who's on each
# team) for github.com/cloudnative-pg. Pure machine truth — like
# managed-repos.yaml, nothing here is a policy decision, just what GitHub
# currently reports.
#
# Deliberately does NOT list which repos each team has access to — that's
# per-project information, and per-project information belongs in a file
# ordered by project, not repeated under every team here. See
# componentowners-policy.yaml (per-repo CODEOWNERS teams/users) and
# org-policy.yaml (teams that get admin everywhere, org-wide, without
# being listed per-repo at all) for where repo access is actually tracked.
#
# Requires: gh (authenticated, org owner or admin — org member listing by
# role needs elevated access), jq
set -uo pipefail

ORG="cloudnative-pg"
INFRA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="$INFRA_ROOT/teams.yaml"

command -v gh >/dev/null 2>&1 || { echo "error: gh CLI is required" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "error: jq is required" >&2; exit 1; }

echo "Fetching org owners/members..." >&2
owners_json="$(gh api -X GET "orgs/${ORG}/members" -f role=admin)"
members_json="$(gh api -X GET "orgs/${ORG}/members" -f role=member)"

echo "Fetching teams..." >&2
teams_json="$(gh api "orgs/${ORG}/teams")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Team roster snapshot for github.com/${ORG}"
  echo "#"
  echo "# Generated by ./update-teams.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not"
  echo "# hand-edit, re-run the script instead."
  echo "#"
  echo "# This is machine truth (live GitHub state), not policy — it says what IS,"
  echo "# not what SHOULD be. Per-repo access is intentionally NOT tracked here —"
  echo "# see componentowners-policy.yaml and org-policy.yaml instead."
  echo "#"
  echo "# org_owners: GitHub org \"owner\" role — full org administration rights,"
  echo "# independent of any team membership. Note some owners here are not on"
  echo "# the 'admins' team below (e.g. Linux Foundation/CNCF staff accounts with"
  echo "# org-owner access for compliance, not project administration)."
  echo "# org_members: org members with no elevated org-level role."
  echo
  echo "org_owners:"
  echo "$owners_json" | jq -r '.[].login' | sort | while read -r login; do echo "  - $login"; done

  echo
  echo "org_members:"
  echo "$members_json" | jq -r '.[].login' | sort | while read -r login; do echo "  - $login"; done

  echo
  echo "teams:"
} > "$tmp"

echo "$teams_json" | jq -r '.[].slug' | while read -r slug; do
  echo "  Fetching team: $slug" >&2
  team_detail="$(echo "$teams_json" | jq -c --arg slug "$slug" '.[] | select(.slug==$slug)')"
  name="$(echo "$team_detail" | jq -r '.name')"
  description="$(echo "$team_detail" | jq -r '.description // ""' | sed 's/"/\\"/g')"
  privacy="$(echo "$team_detail" | jq -r '.privacy')"
  default_permission="$(echo "$team_detail" | jq -r '.permission')"

  members="$(gh api "orgs/${ORG}/teams/${slug}/members" --jq '[.[].login] | sort | .[]' 2>/dev/null)"

  {
    echo "  - slug: $slug"
    echo "    name: \"$name\""
    echo "    description: \"$description\""
    echo "    privacy: $privacy"
    echo "    default_permission: $default_permission"
    echo "    members:"
    if [ -n "$members" ]; then
      echo "$members" | while read -r m; do echo "      - $m"; done
    else
      echo "      []"
    fi
  } >> "$tmp"
done

mv "$tmp" "$OUTPUT"
trap - EXIT
team_count=$(echo "$teams_json" | jq 'length')
echo "Wrote $team_count teams to $OUTPUT" >&2
