#!/usr/bin/env bash
#
# Rebuilds managed-repos.yaml: the list of github.com/cloudnative-pg
# repositories that are (a) not archived and (b) actually cloned as a
# *sibling* of this cnpg-infra checkout (i.e. cnpg-infra and every managed
# repo share the same parent directory — see bootstrap.sh). This is the
# scope every other script here treats as "repos I manage" — re-run this
# script to refresh it rather than hand-editing the YAML.
#
# Requires: gh (authenticated), jq
set -euo pipefail

ORG="cloudnative-pg"
INFRA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE_ROOT="$(cd "$INFRA_ROOT/.." && pwd)"
OUTPUT="$INFRA_ROOT/generated/managed-repos.yaml"

command -v gh >/dev/null 2>&1 || { echo "error: gh CLI is required" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "error: jq is required" >&2; exit 1; }

repos_json=$(gh repo list "$ORG" --limit 500 --json name,isArchived,url,description)

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Managed repositories under github.com/${ORG}"
  echo "#"
  echo "# Generated by ./$(basename "$0") on $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not hand-edit,"
  echo "# re-run the script instead."
  echo "#"
  echo "# Scope: non-archived ${ORG} repositories that have a local clone in this"
  echo "# directory whose 'origin' remote actually points back to that repository."
  echo "# Anything else here (personal forks, loose reference files, ephemeral"
  echo "# per-advisory GHSA repos, org repos with no local clone) is intentionally"
  echo "# excluded."
  echo "repositories:"
} > "$tmp"

count=0
while IFS=$'\t' read -r name url description; do
  # Only include repos that are actually cloned locally, as a sibling of cnpg-infra...
  [ -d "$WORKSPACE_ROOT/$name/.git" ] || continue
  # ...and whose remote genuinely points at this org repo (not a same-named fork).
  local_url="$(git -C "$WORKSPACE_ROOT/$name" remote get-url origin 2>/dev/null || true)"
  case "$local_url" in
    *"github.com/${ORG}/${name}"*|*"github.com/${ORG}/${name}.git") ;;
    *) continue ;;
  esac

  esc_description="$(printf '%s' "$description" | sed 's/\\/\\\\/g; s/"/\\"/g')"

  {
    echo "  - name: $name"
    echo "    path: $name"
    echo "    url: $url"
    echo "    description: \"$esc_description\""
  } >> "$tmp"
  count=$((count + 1))
done < <(echo "$repos_json" | jq -r 'sort_by(.name) | .[] | select(.isArchived == false) | [.name, .url, (.description // "")] | @tsv')

mv "$tmp" "$OUTPUT"
trap - EXIT
echo "Wrote $count repositories to $OUTPUT"
